esphome:
  name: fancontroller_0

esp32:
  board: esp32dev
  variant: esp32


wifi:
  ssid: !secret ssid
  password: !secret pass
  fast_connect: true

i2c:
  scl: GPIO15
  sda: GPIO2

web_server:
api:
logger:
